apiVersion: v1
kind: Service
metadata:
  name: user-ms-svc
  labels:
    run: user-ms
spec:
  ports:
  - port: 58081
    targetPort: 58081
  selector:
    app: user-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      containers:
      - name: user-ms
        image: usnvregistry.azurecr.io/advassess-useradmin:latest
        command:
          - "java"
          - "-jar"
          - "/tmp/userServiceApplication-0.0.1-SNAPSHOT.jar"
        ports:
        - containerPort: 58081