apiVersion: v1
kind: Service
metadata:
  name: question-ms-svc
  labels:
    run: question-ms
spec:
  ports:
  - port: 58082
    targetPort: 58082
  selector:
    app: question-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-ms
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: question-ms
  template:
    metadata:
      labels:
        app: question-ms
    spec:
      containers:
      - name: question-ms
        image: usnvregistry.azurecr.io/advassess-useradmin-questionms:Latest
        command:
          - "java"
          - "-jar"
          - "/tmp/QuestionService-0.0.1-SNAPSHOT.jar"
        ports:
        - containerPort: 58082