apiVersion: v1
kind: Service
metadata:
  name: assessment-ms-svc
  labels:
    run: assessment-ms
spec:
  ports:
  - port: 58080
    targetPort: 58080
  selector:
    app: assessment-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-ms
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: assessment-ms
  template:
    metadata:
      labels:
        app: assessment-ms
    spec:
      containers:
      - name: assessment-ms
        image: usnvregistry.azurecr.io/advassess-useradmin-assessmentms:latest
        command:
          - "java"
          - "-jar"
          - "/tmp/projectexample-0.0.1-SNAPSHOT.jar"
        ports:
        - containerPort: 58080